context:
  version: "0.9.15"
  python_min: "3.12"

package:
  name: py-asyncutils
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/py_asyncutils/py_asyncutils-${{ version }}.tar.gz
  sha256: 03a0ab73b359a86ca6285ca201cf9fcc475c5f30770c9ee2f4be81467978ed4e

build:
  script: uv pip install --python ${{ PYTHON }} --no-deps -vv .
  number: 0
  noarch: python
  python:
    entry_points:
      - asyncutils = asyncutils.cli:run
      - autils = asyncutils.cli:run

requirements:
  host:
    - python ${{ python_min }}.*
    - uv
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - asyncutils
      pip_check: true
  - script:
      - python -m asyncutils -?
      - asyncutils -v
      - autils -h

about:
  homepage: https://github.com/jonathandung/asyncutils
  summary: 'Your go-to async toolkit library.'
  description: |
    You may see this as yet another async library, but with its 30+ submodules each serving different use cases, asyncutils aims to suit
    your every need for recurring patterns in async, both high-level and low-level.
    Another merit is that is starts up fast (indeed, the asyncio import takes up 95% of the time required to load the module), and comes
    with an extensible REPL console for lightning-speed prototyping and testing, and a beautiful command line. An 'asyncutils' command
    is made available to run the console, for which 'autils' is an alias.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/jonathandung/asyncutils

extra:
  recipe-maintainers:
    - jonathandung
